module.exports = {
	created: "created success",
	updated: "updated success",
	exist: "Already exists",
	notRegistered: "User available to create",
	successfull: "successfull",
	mailSend: "Verification email sent!!",
	userLoggedIn: "User Logged In Successfully.",
	userLoggedOut: "User Logged Out Successfully.",
	userNotLoggedOut: "User Logged Out Not Successfully.",
	alreadyLoggedOut: "Please login again to continue",
	userInvalidCredentials: "Invalid credentials; please try again",    
	userInvalidToken: "Invalid token provided.",
	userValidToken: "Token is valid.",
	userNotVerified: "Invalid code",
	userVerified: "Verified user.",
	codeExpired: "The entered code has expired",
	refferralNotVerified: "Invalid referral code",
	referralVerified: "Verified referral code.",
	userSuspended: "Currently suspended.",
	userNotFound: "Email doesn't match, please enter correct one.",
	userNotExist: "User Not Found.",
	userIllegalAccess: "User does not have enough permission.",
	get: "Listed Successfully!!",
	invalidPassword: "Password is incorrect, please try again",
	existsEmail: "Email ID already exists",
	existsSignup: "User is already registered.",
	existsWaitlist: "You are already on the waitlist.\nAdmin will reach out to you shortly",
	codesend: "resend success",
	emailsend: "Four Digit Verification Code Send Successfully",
	userAlreadyVerified: "Email Already verfied",
	notificationTriggered: "Notification Triggered Successfully",
	emailVerified: "Email Verification",
	emailVerifiedMessage: "Email Successfully Verified",
	emailVerifiedbody: "Your Email have been verified successfully",
	emailIsNotRegistered : "This Email ID is not registered, please enter a registered email address.",
	emailAddUserSub : "You have been successfully added as a new user",
	emailAddUserMessage : "Your temporary password is ",
	termsAccepted: "Terms and Conditions Accepted.",  
	termsNotAccepted:"Please Verify Email",
	termsExists:"Terms and Conditions Already Accepted",
	profileFailed:"Please Accept Terms  and Conditions",
	profileExists:"Profile Already Exists,please login and edit your profile",
	loginFailed:"Please Create Your Basic Profile",
	codeVerified:"Four Digit Verified",
	codeNotVerified:"Invalid code",
	passwordExists:"New password cannot be the same as a previous password",
	passwordUpdate:"reset password successfully",
	noRecord:"Data Not Found",
	generateSuccess:"Referral code Code Generated Successfully",
	adminInvalidCredentials:"Password is incorrect. Please try to reset password",
	adminInvalid:"User is not found",
	topicExists:"Topic Name Already Exists",
	countExists:"Help Topic Limit Reached",
	emailNotFound:"There is no registered account associated with this email",
	noQuestionFound:"You have not submittted any open questions at this moment.",
	dataNotFound:"No Data Found",
	deleted:"Deleted success",
	notDeleted:"Not able to Delete",
	Exists:"Already Exists",
	notUpdated:"Data Not Updated",
	oldPasswordNotMatched:"Your Old password is wrong",
	changepassword:"Your Password changed successfully",
	pinnedQuestionRemoved:"Pinned Question removed",
	accountDeleted:"DELETED",
	accountSuspended:"This account is suspended please contact Venncommunity",
	existsUserSignup:"There is already an account associated with this email",
	invalidCountryId:"Invalid Country Id",
	invalidStateId:"Invalid State Id",
	userAlreadyExits: "User already exists Please sign in to your account",
	notHaveAdminPrivilage:"This is user doesn't have admin privilage",
	notExistUser:"There is no registered account associated with this email",

	100: "Continue",
	101: "Switching Protocols",
	102: "Processing", // RFC2518
	103: "Early Hints",
	200: "OK",
	201: "Created",
	202: "Accepted",
	203: "Non-Authoritative Information",
	204: "No Content",
	205: "Reset Content",
	206: "Partial Content",
	207: "Multi-Status", // RFC4918
	208: "Already Reported", // RFC5842
	226: "IM Used", // RFC3229
	300: "Multiple Choices",
	301: "Moved Permanently",
	302: "Found",
	303: "See Other",
	304: "Not Modified",
	305: "Use Proxy",
	307: "Temporary Redirect",
	308: "Permanent Redirect", // RFC7238
	400: "Bad Request",
	401: "Unauthorized",
	402: "Payment Required",
	403: "Forbidden",
	404: "Not Found",
	405: "Method Not Allowed",
	406: "Not Acceptable",
	407: "Proxy Authentication Required",
	408: "Request Timeout",
	409: "Conflict",
	410: "Gone",
	411: "Length Required",
	412: "Precondition Failed",
	413: "Payload Too Large",
	414: "URI Too Long",
	415: "Unsupported Media Type",
	416: "Range Not Satisfiable",
	417: "Expectation Failed",
	418: "I'm a teapot", // RFC2324
	421: "Misdirected Request", // RFC7540
	422: "Unprocessable Entity", // RFC4918
	423: "Locked", // RFC4918
	424: "Failed Dependency", // RFC4918
	425: "Reserved for WebDAV advanced collections expired proposal", // RFC2817
	426: "Upgrade Required", // RFC2817
	428: "Precondition Required", // RFC6585
	429: "Too Many Requests", // RFC6585
	431: "Request Header Fields Too Large", // RFC6585
	451: "Unavailable For Legal Reasons", // RFC7725
	500: "Internal Server Error",
	501: "Not Implemented",
	502: "Bad Gateway",
	503: "Service Unavailable",
	504: "Gateway Timeout",
	505: "HTTP Version Not Supported",
	506: "Variant Also Negotiates", // RFC2295
	507: "Insufficient Storage", // RFC4918
	508: "Loop Detected", // RFC5842
	510: "Not Extended", // RFC2774
	511: "Network Authentication Required", // RFC6585
};
